name: Build MinGW32 MSVCRT (Arch)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: archlinux-latest
    container:
      image: archlinux:base-devel
    steps:
      - name: Update pacman and install dependencies
        run: |
          pacman -Sy --noconfirm
          pacman -S --noconfirm base-devel git wget tar bison flex texinfo gcc

      - name: clone repository
        uses: actions/checkout@v4

      - name: Runs the build script
        run: |
          chmod +x compile-mingw32.sh
          ./compile-mingw32.sh

      - name: Verify installed binaries
        run: |
          /opt/mingw32-msvcrt/bin/i686-w64-mingw32-gcc --version
